<ivy-module version="2.4">
    <info organisation="de.unitrier.st" module="codesparks-pmd-demo"/>
    <dependencies>
        <dependency org="net.sourceforge.pmd" name="pmd-core" rev="6.29.0" transitive="false"/>
        <dependency org="net.sourceforge.pmd" name="pmd-java" rev="6.29.0" transitive="false"/>
        <!-- Needs to be added as it is a transitive dependency of pmd 6.29. Must also be set as module library such
         that it is also copied to the lib folder of the plugin -->
        <dependency org="org.ow2.asm" name="asm" rev="9.0-beta"/>
    </dependencies>
</ivy-module>